services:
  we-lunch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: we-lunch
    ports:
      - "4504:4504"  # 노출할 포트
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true